"""Initial migration.

Revision ID: 56859057b27a
Revises: 
Create Date: 2021-05-22 00:36:54.277556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56859057b27a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canidates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=120), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=120), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('past_experience', sa.Text(), nullable=False),
                    sa.Column('reason', sa.Text(), nullable=False),
                    sa.Column('phone_number', sa.Unicode(
                        length=11), nullable=True),
                    sa.Column('department', sa.String(
                        length=120), nullable=False),
                    sa.Column('year', sa.String(length=120), nullable=False),
                    sa.Column('domain', sa.String(length=120), nullable=False),
                    sa.Column('status', sa.String(length=120), nullable=False),
                    sa.Column('remarks', sa.Text(), nullable=False),
                    sa.Column('remarks_by', sa.String(
                        length=120), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('email')
                    )
    registration_controls = op.create_table('registration_controls',
                                            sa.Column('id', sa.Integer(),
                                                      nullable=False),
                                            sa.Column('isRegistration',
                                                      sa.Boolean(), nullable=False),
                                            sa.PrimaryKeyConstraint('id')
                                            )

    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=True),
                    sa.Column('password', sa.String(
                        length=100), nullable=True),
                    sa.Column('name', sa.String(length=1000), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###

    op.bulk_insert(registration_controls, [{'id': 1, 'isRegistration': True}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('registration_controls')
    op.drop_table('canidates')
    # ### end Alembic commands ###
